/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.quarkus.component.http.http.it;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

import io.quarkus.test.common.QuarkusTestResourceLifecycleManager;
import org.testcontainers.containers.BindMode;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.DockerImageName;

/**
 * Test resource that starts an nginx container with PQC hybrid certificates.
 *
 * Certificates are generated via @PQCCertificates annotation on the test class.
 * This resource only handles nginx container lifecycle.
 */
public class PqcNginxTestResource implements QuarkusTestResourceLifecycleManager {
    private static final String CERT_DIR = "target/certs/bctls-nginx";
    private static final String TRUSTSTORE_PASSWORD = "changeit";
    // Use standard nginx (not OQS) to test BCTLS integration
    // OQS-OpenSSL is incompatible with BouncyCastle JSSE at the protocol level
    private static final String NGINX_IMAGE = "nginx:alpine";

    private GenericContainer<?> container;

    @Override
    public Map<String, String> start() {
        try {
            // Skip if testcontainers are disabled
            if (Boolean.parseBoolean(System.getProperty("skip-testcontainers-tests", "false"))) {
                return Map.of();
            }

            Path certDirPath = Path.of(CERT_DIR);

            // Certificates should have been generated by @PQCCertificates annotation
            // Verify they exist before starting nginx
            File certFile = certDirPath.resolve("nginx-hybrid-pqc-cert.pem").toFile();
            File keyFile = certDirPath.resolve("nginx-hybrid-pqc-key.pem").toFile();
            File truststoreFile = certDirPath.resolve("nginx-hybrid-pqc-truststore.p12").toFile();

            if (!certFile.exists() || !keyFile.exists()) {
                throw new IllegalStateException(
                        "PQC certificates not found. Expected @PQCCertificates to generate them at: " + CERT_DIR);
            }

            // Write nginx configuration
            // Certificate contains both RSA (primary) and Dilithium2/ML-DSA (alternative) keys
            String nginxConfig = """
                    server {
                        listen 4433 ssl;
                        server_name localhost;
                        ssl_certificate /certs/nginx-hybrid-pqc-cert.pem;
                        ssl_certificate_key /certs/nginx-hybrid-pqc-key.pem;
                        ssl_protocols TLSv1.3 TLSv1.2;
                        location /test {
                            return 200 "Hybrid RSA+Dilithium(ML-DSA) certificate validated";
                            add_header Content-Type text/plain;
                        }
                    }
                    """;

            File nginxConfigFile = certDirPath.resolve("default.conf").toFile();
            Files.writeString(nginxConfigFile.toPath(), nginxConfig);

            // Start standard nginx container
            container = new GenericContainer<>(DockerImageName.parse(NGINX_IMAGE))
                    .withExposedPorts(4433)
                    .withFileSystemBind(certDirPath.toAbsolutePath().toString(), "/certs", BindMode.READ_ONLY)
                    .withFileSystemBind(nginxConfigFile.getAbsolutePath(), "/etc/nginx/conf.d/default.conf",
                            BindMode.READ_ONLY)
                    .withLogConsumer(frame -> System.out.print(frame.getUtf8String()))
                    .waitingFor(Wait.forListeningPort());

            container.start();

            // Return configuration properties
            Map<String, String> result = new LinkedHashMap<>();
            result.put("pqc.nginx.host", container.getHost());
            result.put("pqc.nginx.port", String.valueOf(container.getMappedPort(4433)));
            result.put("pqc.nginx.truststore.path", "file://" + truststoreFile.getAbsolutePath());
            result.put("pqc.nginx.truststore.password", TRUSTSTORE_PASSWORD);

            return result;
        } catch (Exception e) {
            throw new RuntimeException("Failed to start PQC nginx test resource", e);
        }
    }

    @Override
    public void stop() {
        if (container != null) {
            container.stop();
        }
    }
}
