-- #SET TERMINATOR ;
-- CREATE TABLE camel(
--     id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     species BLOB(50) NOT NULL);
CREATE TABLE EVENTS7 ( 'ID' INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) , 'NAME' VARCHAR (256) )
-- CREATE TABLE camel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, species VARCHAR ( 50 ) NOT NULL);
-- for consumer
-- DROP TABLE IF EXISTS projects
-- create table projects (id integer primary key, project varchar(25), license varchar(5), processed BOOLEAN);
--
-- -- idempotent repo
-- DROP TABLE IF EXISTS CAMEL_MESSAGEPROCESSED
-- CREATE TABLE CAMEL_MESSAGEPROCESSED ( processorName VARCHAR(255), messageId VARCHAR(100), createdAt TIMESTAMP )
--
-- -- aggregation repo
-- DROP TABLE IF EXISTS aggregation
-- CREATE TABLE aggregation (id varchar(255) NOT NULL, exchange BYTEA NOT NULL, version BIGINT NOT NULL, constraint aggregation_pk PRIMARY KEY (id));
-- DROP TABLE IF EXISTS aggregation_completed
-- CREATE TABLE aggregation_completed (id varchar(255) NOT NULL, exchange BYTEA NOT NULL, version BIGINT NOT NULL, constraint aggregation_completed_pk PRIMARY KEY (id));

