#
#Wed Feb 19 11:29:16 CET 2025
quarkus.s3.sync-client.type=apache
mailslurp.api.key=${MAILSLURP_API_KEY}
quarkus.dynamodb.sync-client.type=apache
quarkus.s3.checksum-validation=false
quarkus.ses.sync-client.type=apache
quarkus.sqs.sync-client.type=apache
quarkus.devservices.enabled=false
quarkus.sns.sync-client.type=apache
