cq.google-secrets-manager.path-to-service-account-key=${GOOGLE_SERVICE_ACCOUNT_KEY}
cq.google-secrets-manager.project-name=${GOOGLE_PROJECT_NAME}
camel.vault.gcp.serviceAccountKey=file:${GOOGLE_SERVICE_ACCOUNT_KEY}
camel.vault.gcp.projectId=${GOOGLE_PROJECT_NAME}
