= Generating keystores

=== Generate keys.

>>>>> ca

openssl genrsa -out cxfca.key 2048
openssl req -x509 -new -key cxfca.key -nodes -out cxfca.pem -config cxfca-openssl.cnf -days 3650 -extensions v3_req
openssl req -new -subj '/O=apache.org/OU=eng/CN=cxfca' -x509 -key cxfca.key -out cxfca.crt

>>>>> gen keys + certs

openssl genrsa -out myservice.key 2048
openssl req -new -subj '/O=apache.org/L=camel-ftp/OU=eng/CN=myservice' -key myservice.key -out myservice.csr
openssl x509 -req -in myservice.csr -CA cxfca.pem -CAkey cxfca.key -CAcreateserial -out myservice.crt

openssl genrsa -out mysts.key 2048
openssl req -new -subj '/O=apache.org/L=camel-ftp/OU=eng/CN=mysts' -key mysts.key -out mysts.csr
openssl x509 -req -in mysts.csr -CA cxfca.pem -CAkey cxfca.key -CAcreateserial -out mysts.crt

openssl genrsa -out myclient.key 2048
openssl req -new -subj '/O=apache.org/L=camel-ftp/OU=eng/CN=myclient' -key myclient.key -out myclient.csr
openssl x509 -req -in myclient.csr -CA cxfca.pem -CAkey cxfca.key -CAcreateserial -out myclient.crt

openssl genrsa -out actasclient.key 2048
openssl req -new -subj '/O=apache.org/L=camel-ftp/OU=eng/CN=actasclient' -key actasclient.key -out actasclient.csr
openssl x509 -req -in actasclient.csr -CA cxfca.pem -CAkey cxfca.key -CAcreateserial -out actasclient.crt

>>>>> servicestore

openssl pkcs12 -export -in myservice.crt -inkey myservice.key -certfile cxfca.crt -name "myservicekey" -out servicestore.p12 -passout pass:sspass -keypbe aes-256-cbc -certpbe aes-256-cbc
keytool -import -trustcacerts -alias mystskey -file mysts.crt -keystore servicestore.p12

>>> stsstore

openssl pkcs12 -export -in mysts.crt -inkey mysts.key -certfile cxfca.crt -name "mystskey" -out stsstore.p12 -passout pass:stsspass -keypbe aes-256-cbc -certpbe aes-256-cbc
keytool -import -trustcacerts -alias myservicekey -file myservice.crt -keystore stsstore.p12
keytool -import -trustcacerts -alias myclientkey -file myclient.crt -keystore stsstore.p12
keytool -import -trustcacerts -alias myactaskey -file actasclient.crt -keystore stsstore.p12

>>> clientstore

openssl pkcs12 -export -in myclient.crt -inkey myclient.key -certfile cxfca.crt -name "myclientkey" -out clientstore.p12 -passout pass:cspass -keypbe aes-256-cbc -certpbe aes-256-cbc
keytool -import -trustcacerts -alias myservicekey -file myservice.crt -keystore clientstore.p12
keytool -import -trustcacerts -alias mystskey -file mysts.crt -keystore clientstore.p12
keytool -import -trustcacerts -alias actaskey -file actasclient.crt -keystore clientstore.p12