
= WS-Security and WS-SecurityPolicy tests

== WS-SecurityPolicy

We test in two ways how the SOAP service endpoints are deployed: the Camel way and the Quariverse CXF way.

=== The Camel way

* I.e. there is a Camel route with `from("cxf:...")`
* See `WsSecurityPolicyServerRoutes` and `WssSecurityPolicyHelloServiceImpl`

=== The Quariverse CXF way

* I.e. they are mapped to an URI path via Quariverse CXF settings in `application.properties`
* The service method then forwards to a Camel route defined in `WsSecurityPolicyServerRoutesCxfWay`
* See also `WssSecurityPolicyHelloServiceCxfWayImpl`
* This way may come in handy in situations when the Camel way does not work properly,
  such as https://github.com/apache/camel-quarkus/issues/4291

= FIPS

Please use profile `fips` if running the tests in the FIPS-enabled environment. The tests have to leverage BouncyCastle-fips dependency instead of standard BouncyCastle.

= Generating keystores

Run following commands in a folder with `cxfca-openssl.config`.

```
echo "*** Generate keys ***"
openssl genrsa -out alice.key 2048
openssl genrsa -out bob.key 2048

echo "*** Certificate authority ***"
echo "When prompted for certificate information, confirm default values."
openssl genrsa -out cxfca.key 2048
openssl req -x509 -new -key cxfca.key -nodes -out cxfca.pem -config cxfca-openssl.cnf -days 10000 -extensions v3_req
openssl req -new -subj '/O=apache.org/OU=eng (NOT FOR PRODUCTION)/CN=cxfca' -x509 -key cxfca.key -days 10000 -out cxfca.crt

echo "*** Generate certificates ***"
openssl req -new -subj '/O=apache.org/OU=eng (NOT FOR PRODUCTION)/CN=cxfca' -x509 -key cxfca.key -out cxfca.crt
openssl req -new -subj '/O=apache.org/OU=eng (NOT FOR PRODUCTION)/CN=alice' -key alice.key -out alice.csr
openssl x509 -req -in alice.csr -CA cxfca.pem -CAkey cxfca.key -CAcreateserial -days 10000 -out alice.crt
openssl req -new -subj '/O=apache.org/OU=eng (NOT FOR PRODUCTION)/CN=bob' -key bob.key -out bob.csr
openssl x509 -req -in bob.csr -CA cxfca.pem -CAkey cxfca.key -CAcreateserial -days 10000 -out bob.crt

echo "*** Export keystores ***"
openssl pkcs12 -export -in alice.crt -inkey alice.key -certfile cxfca.crt -name "alice" -out alice.p12 -passout pass:password -keypbe aes-256-cbc -certpbe aes-256-cbc
openssl pkcs12 -export -in bob.crt -inkey bob.key -certfile cxfca.crt -name "bob" -out bob.p12 -passout pass:password -keypbe aes-256-cbc -certpbe aes-256-cbc

echo "When prompted for password, type 'password'."
echo "When prompted whether to trust the certificate, type 'yes'."
keytool -import -trustcacerts -alias bob -file bob.crt -keystore alice.p12
keytool -import -trustcacerts -alias alice -file alice.crt -keystore bob.p12
```