package org.apache.camel.quarkus.component.jt400.it;

import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
public class Jt400Test {

    //    @Test
    //    public void loadComponentJt400() {
    //        /* A simple autogenerated test */
    //        RestAssured.get("/jt400/load/component/jt400")
    //                .then()
    //                .statusCode(200);
    //    }
}
