## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------
quarkus.native.resources.includes=rag/*
quarkus.http.test-timeout=120S

# This can be handy for detecting output from DefaultMcpClient npx process in case of eg. slow Windows machine.
# quarkus.log.category."dev.langchain4j.mcp.client.transport.stdio".level=DEBUG


quarkus.langchain4j.ollama.nomicEmbed.embedding-model.model-name=nomic-embed-text
quarkus.langchain4j.ollama.nomicEmbed.embedding-model.temperature=0.3
#quarkus.langchain4j.ollama.nomicEmbed.embedding-model.log-requests=true
#quarkus.langchain4j.ollama.nomicEmbed.embedding-model.log-responses=true
quarkus.langchain4j.ollama.nomicEmbed.base-url=${langchain4j.ollama.base-url}

quarkus.langchain4j.ollama.granite4Model.chat-model.model-name=granite4:3b
quarkus.langchain4j.ollama.granite4Model.chat-model.temperature=0.3
#quarkus.langchain4j.ollama.granite4Model.chat-model.log-requests=true
#quarkus.langchain4j.ollama.granite4Model.chat-model.log-responses=true
quarkus.langchain4j.ollama.granite4Model.timeout=60
quarkus.langchain4j.ollama.granite4Model.base-url=${langchain4j.ollama.base-url}


quarkus.langchain4j.ollama.ollamaOrcaMiniModel.chat-model.model-name=orca-mini
quarkus.langchain4j.ollama.ollamaOrcaMiniModel.chat-model.temperature=0.4
#quarkus.langchain4j.ollama.ollamaOrcaMiniModel.chat-model.log-requests=true
#quarkus.langchain4j.ollama.ollamaOrcaMiniModel.chat-model.log-responses=true
quarkus.langchain4j.ollama.ollamaOrcaMiniModel.timeout=60
quarkus.langchain4j.ollama.ollamaOrcaMiniModel.base-url=${langchain4j.ollama.base-url}