/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.quarkus.component.jt400.it;

import io.quarkus.test.junit.QuarkusTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.camel.util.CollectionHelper;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.Test;

@QuarkusTest
public class Jt400Test {

    @Test
    public void loadComponentJt400() {
        /* A simple autogenerated test */
        RestAssured.get("/jt400/load/component/jt400")
                .then()
                .statusCode(200);
    }

    @Test
    public void testGetData() {
        prepareMockReply(Jt400Resource.ReplyType.ok);
        prepareMockReply(Jt400Resource.ReplyType.request);
        prepareMockReply(Jt400Resource.ReplyType.ok);
        prepareMockReply(Jt400Resource.ReplyType.normal, 0x8003, "mocked jt400", "Hello from mocked jt400!", "MYKEY");

        /* A simple autogenerated test */
        RestAssured.get("/jt400/get/data")
                .then()
                .statusCode(200)
                .body(Matchers.equalTo("Hello from mocked jt400!"));
    }

    private void prepareMockReply(Jt400Resource.ReplyType replyType,
            Integer hashCode,
            String senderInformation,
            String entry,
            String key) {
        //prepare mock data
        RestAssured.given()
                .contentType(ContentType.JSON)
                .body(CollectionHelper.mapOf("replyType", replyType.name(),
                        "hashCode", hashCode,
                        "senderInformation", senderInformation,
                        "entry", entry,
                        "key", key))
                .post("/jt400/put/mockResponse")
                .then()
                .statusCode(200);
    }

    private void prepareMockReply(Jt400Resource.ReplyType replyType) {
        //prepare mock data
        RestAssured.given()
                .body(CollectionHelper.mapOf("replyType", replyType.name()))
                .contentType(ContentType.JSON)
                .post("/jt400/put/mockResponse")
                .then()
                .statusCode(200);
    }
}
