#profile adds SunPKCS11-NSS-FIPS or BCFIPS provider
${cq-security-provider}

quarkus.log.category."org.apache.sshd".min-level=TRACE
quarkus.log.category."org.apache.sshd.client.session".level=DEBUG
#quarkus.log.category."org.apache.camel.component.ssh".level=DEBUG

quarkus.native.resources.includes=edDSA/**
